const Types = {
    ADD_NEW_MESSAGE_ACTION: 'ADD_NEW_MESSAGE_ACTION',
    SET_USERNAME_ACTION: 'SET_USERNAME_ACTION',
    LOG_MESSAGE: 'LOG_MESSAGE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
}
export default Types